build: fix cancel when merge conflict. (#632)
* build: fix cancel when merge conflict.

* chore: update slack link.

diff --git a/.github/workflows/merge-from-milestone.yml b/.github/workflows/merge-from-milestone.yml
--- a/.github/workflows/merge-from-milestone.yml
+++ b/.github/workflows/merge-from-milestone.yml
@@ -11,15 +11,15 @@ on:
       milestone_name:
         description: "Milestone name to collect closed PRs from"
         required: true
-        default: "v3.8.4"
+        default: "v1.8.5"
       target_branch:
         description: "Target branch to merge the consolidated PR"
         required: true
-        default: "pre-release-v3.8.4"
+        default: "pre-release-v1.8.5"
 
 env:
-  MILESTONE_NAME: ${{ github.event.inputs.milestone_name || 'v3.8.4' }}
-  TARGET_BRANCH: ${{ github.event.inputs.target_branch || 'pre-release-v3.8.4' }}
+  MILESTONE_NAME: ${{ github.event.inputs.milestone_name || 'v1.8.5' }}
+  TARGET_BRANCH: ${{ github.event.inputs.target_branch || 'pre-release-v1.8.5' }}
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
   LABEL_NAME: cherry-picked
@@ -113,14 +113,33 @@ jobs:
 
               echo "Cherry-picking commit: $merge_commit"
               if ! git cherry-pick "$merge_commit" --strategy=recursive -X theirs; then
-                echo "Cherry-pick encountered conflicts, attempting to continue..."
-                git cherry-pick --continue || { echo "Cherry-pick failed"; exit 1; }
+                echo "Conflict detected for $merge_commit. Resolving with incoming changes."
+                conflict_files=$(git diff --name-only --diff-filter=U)
+                echo "Conflicting files:"
+                echo "$conflict_files"
+
+                for file in $conflict_files; do
+                  if [ -f "$file" ]; then
+                    echo "Resolving conflict for $file"
+                    git add "$file"
+                  else
+                    echo "File $file has been deleted. Skipping."
+                    git rm "$file"
+                  fi
+                done
+
+                echo "Conflicts resolved. Continuing cherry-pick."
+                git cherry-pick --continue || { echo "Cherry-pick failed, but continuing to create PR."; }
+              else
+                echo "Cherry-pick successful for commit $merge_commit."
               fi
 
               git remote set-url origin "https://${BOT_TOKEN}@github.com/${{ github.repository }}.git"
               
               echo "Pushing branch: $cherry_pick_branch"
-              git push origin $cherry_pick_branch --force || { echo "Push failed"; exit 1; }
+              if ! git push origin $cherry_pick_branch --force; then
+                echo "Push failed, but continuing to create PR..."
+              fi
 
               new_pr_title="$pr_title [Created by @$pr_creator from #$pr_number]"
               new_pr_body="$pr_body
